version: '3.8'

services:
  api:
    build: ./backend
    container_name: laravel_api
    restart: unless-stopped
    depends_on:
      - controller
      - database
      - searcher
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=database
      - DB_DATABASE=mydb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
    # ports:
    #   - "9000:9000"

  controller:
    image: nginx:latest
    container_name: load_balancer
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    ports:
      - "8005:80"

  database:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=password
    networks:
      - app_network
    ports:
      - "9200:9200"
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
